name: PRB_Macos
env:
  SAIL_CLIENT_ID: ${{secrets.CLI_TEST_TENANT_CLIENT_ID}}
  SAIL_CLIENT_SECRET: ${{secrets.CLI_TEST_TENANT_CLIENT_SECRET}}
  SAIL_BASE_URL: https://css-255.api.identitynow.com

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: macos-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sailpoint-cli-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test
        run: go test -v -count=1 ./...

      - name: Install
        run: make install

      - name: Init connector and customizer project
        run: |
          sail conn init connectorTest
          sail conn customizers init customizerTest

      - name: Test connector project from init command
        working-directory: ./connectorTest
        run: |
          npm install
          npm run test
          npm run pack-zip

      - name: Test customizer project from init command
        working-directory: ./customizerTest
        run: |
          npm install
          npm run test
          npm run pack-zip
